name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false
          conda-channels: conda-forge, anaconda
      - run: conda --version
      - run: which python
      - run:
          conda install -y pdal geopandas pytest
      - name: Run tests with pytest
        run: pytest 

